# -*- coding: utf-8 -*-
"""class1-Escape Sequences-Cipperschools

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pLEl3MHobf25vuJzOaQU_m1kKCOXEKDN
"""

#print function
print("hello world")

#Escape sequences

print("line A\nline B")

print("line A\nline B\nline c")

print("name\tSerena")

print("this is blackslash\\")

print("this is double blackslash\\\\")

print("Hell\bo")

print("line A \\n line B")

print("line a \\t  lineb")

print("\",\'")

print("\\","\\'")